<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MotorcycleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('motorcycles')->insert([
            [
                'brand' => 'Aprilia',
                'type' => 'Caponord 1200',
                'licencePlate' => 'VPM-327',
                'year' => 2015,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 125.0,
                'powerkW' => 91.2,
                'engineSize' => 1197,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 145800,
                'trafficDate' => '2028-03-15',
                'location' => '1044 Budapest, Megyeri út 20.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'Mana 850',
                'licencePlate' => 'KYQ-873',
                'year' => 2012,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 75.1,
                'powerkW' => 54.8,
                'engineSize' => 839.3,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 20700,
                'deposit' => 62100,
                'trafficDate' => '2025-07-20',
                'location' => '1096 Budapest, Haller utca 89.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'RS 125',
                'licencePlate' => 'GZR-419',
                'year' => 2006,
                'gearbox' => 'Manuális (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 28.2,
                'powerkW' => 20.6,
                'engineSize' => 124.8,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 99300,
                'trafficDate' => '2026-11-08',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'RSV4 Factory',
                'licencePlate' => 'PNB-672',
                'year' => 2010,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 177.6,
                'powerkW' => 129.6,
                'engineSize' => 999.6,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 133200,
                'trafficDate' => '2027-04-01',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'SR 160',
                'licencePlate' => 'ZFB-830',
                'year' => 2021,
                'gearbox' => 'Automata',
                'fuel' => 'B',

                'powerLe' => 10.8,
                'powerkW' => 7.9,
                'engineSize' => 160,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 24800,
                'deposit' => 74400,
                'trafficDate' => '2028-12-18',
                'location' => '1103 Budapest, Gyömrői út 50.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'Tuono 125',
                'licencePlate' => 'WLS-456',
                'year' => 2017,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 15.0,
                'powerkW' => 10.9,
                'engineSize' => 124.8,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 31100,
                'deposit' => 93300,
                'trafficDate' => '2029-09-30',
                'location' => '1195 Budapest, Ady Endre út 134.'
            ],
            [
                'brand' => 'Aprilia',
                'type' => 'Tuono 660',
                'licencePlate' => 'TXN-258',
                'year' => 2023,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 95.0,
                'powerkW' => 69.3,
                'engineSize' => 660,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 147900,
                'trafficDate' => '2028-05-22',
                'location' => '1161 Budapest, Rákosi út 88.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'C 400 GT',
                'licencePlate' => 'VUK-739',
                'year' => 2020,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 34.0,
                'powerkW' => 24.8,
                'engineSize' => 350,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 99300,
                'trafficDate' => '2025-10-10',
                'location' => '1096 Budapest, Haller utca 89.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'C Evolution',
                'licencePlate' => 'QRG-590',
                'year' => 2020,
                'gearbox' => 'Automata',
                'fuel' => 'E',
                'powerLe' => 48.0,
                'powerkW' => 35.0,
                'engineSize' => 450,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 101700,
                'trafficDate' => '2026-02-28',
                'location' => '1211 Budapest, Szállító utca 6.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'Concept 101',
                'licencePlate' => 'DJB-831',
                'year' => 2022,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 158.2,
                'powerkW' => 115.5,
                'engineSize' => 1649,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 145200,
                'trafficDate' => '2027-08-14',
                'location' => '1064 Budapest, Podmaniczky utca 63.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'F 800 ST',
                'licencePlate' => 'MRN-472',
                'year' => 2010,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 83.8,
                'powerkW' => 61.2,
                'engineSize' => 798,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 28400,
                'deposit' => 85200,
                'trafficDate' => '2028-01-09',
                'location' => '1148 Budapest, Fogarasi út 45.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'G 310 R',
                'licencePlate' => 'HXB-594',
                'year' => 2019,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 34.0,
                'powerkW' => 24.8,
                'engineSize' => 313,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 126300,
                'trafficDate' => '2029-05-19',
                'location' => '1151 Budapest, Károlyi Sándor út 76.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'K 100 RS',
                'licencePlate' => 'FRY-293',
                'year' => 1991,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 100.0,
                'powerkW' => 73.0,
                'engineSize' => 987,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 15700,
                'deposit' => 47100,
                'trafficDate' => '2025-02-11',
                'location' => '1185 Budapest, Üllői út 780.'
            ],

            [
                'brand' => 'BMW',
                'type' => 'K 1200 RS',
                'licencePlate' => 'LSA-815',
                'year' => 2000,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 130.0,
                'powerkW' => 94.9,
                'engineSize' => 1171,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 114600,
                'trafficDate' => '2025-12-27',
                'location' => '1173 Budapest, Pesti út 237.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'M 1000 RR',
                'licencePlate' => 'RZX-476',
                'year' => 2022,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 205.0,
                'powerkW' => 149.6,
                'engineSize' => 999,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 31400,
                'deposit' => 94200,
                'trafficDate' => '2026-04-16',
                'location' => '1044 Budapest, Megyeri út 20.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'R 100 RS',
                'licencePlate' => 'NQF-580',
                'year' => 1982,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 70.0,
                'powerkW' => 51.1,
                'engineSize' => 979,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 112200,
                'trafficDate' => '2027-11-25',
                'location' => '1205 Budapest, Kossuth Lajos utca 120.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'R 1100 RS',
                'licencePlate' => 'TGM-634',
                'year' => 2001,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 90.0,
                'powerkW' => 65.7,
                'engineSize' => 1085,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 23100,
                'deposit' => 69300,
                'trafficDate' => '2028-06-02',
                'location' => '1205 Budapest, Kossuth Lajos utca 120.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'S 1000 R',
                'licencePlate' => 'PKC-981',
                'year' => 2016,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 160.0,
                'powerkW' => 116.8,
                'engineSize' => 999,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 20800,
                'deposit' => 62400,
                'trafficDate' => '2029-03-21',
                'location' => '1037 Budapest, Bojtár utca 43.'
            ],
            [
                'brand' => 'BMW',
                'type' => 'S 1000 XR',
                'licencePlate' => 'FZP-736',
                'year' => 2016,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 158.2,
                'powerkW' => 115.5,
                'engineSize' => 999,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 123000,
                'trafficDate' => '2028-10-18',
                'location' => '1037 Budapest, Bojtár utca 43.'
            ],
            [
                'brand' => 'Ducati',
                'type' => '1199 Panigale',
                'licencePlate' => 'LKV-915',
                'year' => 2013,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 191.8,
                'powerkW' => 140.0,
                'engineSize' => 1198,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32300,
                'deposit' => 96900,
                'trafficDate' => '2025-03-11',
                'location' => '1195 Budapest, Ady Endre út 134.'
            ],
            [
                'brand' => 'Ducati',
                'type' => '748 R',
                'licencePlate' => 'DMS-158',
                'year' => 2001,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 106.0,
                'powerkW' => 77.4,
                'engineSize' => 748,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 102900,
                'trafficDate' => '2026-07-23',
                'location' => '1012 Budapest, Logodi utca 34.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Hyperstrada',
                'licencePlate' => 'SVY-382',
                'year' => 2014,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 110.0,
                'powerkW' => 80.3,
                'engineSize' => 821.1,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 27900,
                'deposit' => 83700,
                'trafficDate' => '2027-09-07',
                'location' => '1117 Budapest, Szerémi út 67.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Monster SR2 1000',
                'licencePlate' => 'QRT-547',
                'year' => 2006,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 93.9,
                'powerkW' => 68.5,
                'engineSize' => 992,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 105900,
                'trafficDate' => '2028-05-15',
                'location' => '1044 Budapest, Megyeri út 20.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Multistrada 1200',
                'licencePlate' => 'VXZ-290',
                'year' => 2017,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 160.0,
                'powerkW' => 116.8,
                'engineSize' => 1198.4,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 129600,
                'trafficDate' => '2029-10-29',
                'location' => '1117 Budapest, Szerémi út 67.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Panigale V4',
                'licencePlate' => 'NFD-617',
                'year' => 2020,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 214.0,
                'powerkW' => 156.2,
                'engineSize' => 1103,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 112500,
                'trafficDate' => '2028-02-14',
                'location' => '1148 Budapest, Fogarasi út 45.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Scrambler Classic',
                'licencePlate' => 'BXK-329',
                'year' => 2017,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 75.0,
                'powerkW' => 54.7,
                'engineSize' => 803,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 24500,
                'deposit' => 73500,
                'trafficDate' => '2025-06-18',
                'location' => '1161 Budapest, Rákosi út 88.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Scrambler Icon',
                'licencePlate' => 'MQL-875',
                'year' => 2015,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 75.0,
                'powerkW' => 54.7,
                'engineSize' => 803,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 30300,
                'deposit' => 90900,
                'trafficDate' => '2026-09-13',
                'location' => '1239 Budapest, Haraszti út 42.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'ST3',
                'licencePlate' => 'WZG-142',
                'year' => 2005,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 102.0,
                'powerkW' => 74.5,
                'engineSize' => 992,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 147000,
                'trafficDate' => '2027-01-20',
                'location' => '1173 Budapest, Pesti út 237.'
            ],
            [
                'brand' => 'Ducati',
                'type' => 'Superleggera 1199',
                'licencePlate' => 'PFC-693',
                'year' => 2014,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 200.0,
                'powerkW' => 146.0,
                'engineSize' => 1198.4,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 21900,
                'deposit' => 65700,
                'trafficDate' => '2028-08-06',
                'location' => '1077 Budapest, Rottenbiller utca 25.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'Dyna Low Rider',
                'licencePlate' => 'KJR-714',
                'year' => 2015,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 75.1,
                'powerkW' => 54.8,
                'engineSize' => 1690,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 147900,
                'trafficDate' => '2029-12-10',
                'location' => '1151 Budapest, Károlyi Sándor út 76.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'Electra Glide Ultra Classic',
                'licencePlate' => 'YZD-268',
                'year' => 2018,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 90.0,
                'powerkW' => 65.7,
                'engineSize' => 1753.5,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32600,
                'deposit' => 97800,
                'trafficDate' => '2028-04-30',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'FXDR 114',
                'licencePlate' => 'CQV-301',
                'year' => 2020,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 100.0,
                'powerkW' => 73.0,
                'engineSize' => 1868,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 27200,
                'deposit' => 81600,
                'trafficDate' => '2025-11-22',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'Softail Heritage Classic 114',
                'licencePlate' => 'JTL-529',
                'year' => 2020,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 94.0,
                'powerkW' => 68.6,
                'engineSize' => 1868,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 102900,
                'trafficDate' => '2026-05-27',
                'location' => '1037 Budapest, Bojtár utca 43.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'Softail Deluxe',
                'licencePlate' => 'GNB-874',
                'year' => 2018,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 86.0,
                'powerkW' => 62.8,
                'engineSize' => 1745,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 25600,
                'deposit' => 76800,
                'trafficDate' => '2027-03-08',
                'location' => '1037 Budapest, Bojtár utca 43.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'CVO Limited',
                'licencePlate' => 'ZSP-156',
                'year' => 2018,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 105.0,
                'powerkW' => 76.6,
                'engineSize' => 1923,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 145200,
                'trafficDate' => '2028-09-17',
                'location' => '1051 Budapest, Bajcsy-Zsilinszky út 24.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'XR1200',
                'licencePlate' => 'RLV-970',
                'year' => 2010,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 90.0,
                'powerkW' => 65.7,
                'engineSize' => 1202,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 143700,
                'trafficDate' => '2029-02-05',
                'location' => '1239 Budapest, Haraszti út 42.'
            ],
            [
                'brand' => 'Harley-Davidson',
                'type' => 'V-Rod Muscle',
                'licencePlate' => 'HBX-324',
                'year' => 2015,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 119.4,
                'powerkW' => 87.1,
                'engineSize' => 1247,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 30900,
                'deposit' => 92700,
                'trafficDate' => '2028-01-26',
                'location' => '1205 Budapest, Kossuth Lajos utca 120. '
            ],
            [
                'brand' => 'Honda',
                'type' => '400X',
                'licencePlate' => 'XQR-580',
                'year' => 2016,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 45.6,
                'powerkW' => 33.3,
                'engineSize' => 399,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 29700,
                'deposit' => 89100,
                'trafficDate' => '2025-04-05',
                'location' => '1223 Budapest, Nagytétényi út 190.'
            ],
[
                'brand' => 'Honda',
                'type' => 'Ace 125',
                'licencePlate' => 'PLS-193',
                'year' => 2022,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 8.5,
                'powerkW' => 6.2,
                'engineSize' => 124.1,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 20000,
                'deposit' => 60000,
                'trafficDate' => '2026-08-11',
                'location' => '1161 Budapest, Rákosi út 88.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'Activa',
                'licencePlate' => 'FJC-618',
                'year' => 2011,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 8.0,
                'powerkW' => 5.8,
                'engineSize' => 109,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 15100,
                'deposit' => 45300,
                'trafficDate' => '2027-10-12',
                'location' => '1195 Budapest, Ady Endre út 134.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'ADV 160',
                'licencePlate' => 'VWY-267',
                'year' => 2023,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 15.8,
                'powerkW' => 11.5,
                'engineSize' => 157,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 112200,
                'trafficDate' => '2028-07-21',
                'location' => '1103 Budapest, Gyömrői út 50.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'Air Blade 160',
                'licencePlate' => 'KGL-951',
                'year' => 2023,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 15.0,
                'powerkW' => 11.0,
                'engineSize' => 157,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 109500,
                'trafficDate' => '2029-11-04',
                'location' => '1185 Budapest, Üllői út 780.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'ANF 125i Innova',
                'licencePlate' => 'LYT-428',
                'year' => 2007,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 9.0,
                'powerkW' => 6.6,
                'engineSize' => 124.9,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 31200,
                'deposit' => 93600,
                'trafficDate' => '2028-08-29',
                'location' => '1211 Budapest, Szállító utca 6.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 1000 R',
                'licencePlate' => 'RXB-723',
                'year' => 2022,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 143.5,
                'powerkW' => 104.7,
                'engineSize' => 998,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 142200,
                'trafficDate' => '2025-01-07',
                'location' => '1205 Budapest, Kossuth Lajos utca 120.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 125 F',
                'licencePlate' => 'QHN-853',
                'year' => 2023,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 10.7,
                'powerkW' => 7.8,
                'engineSize' => 123.9,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 109200,
                'trafficDate' => '2026-06-15',
                'location' => '1117 Budapest, Szerémi út 67.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 200 X',
                'licencePlate' => 'NFW-291',
                'year' => 2022,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 17.0,
                'powerkW' => 12.4,
                'engineSize' => 184,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 146100,
                'trafficDate' => '2027-12-09',
                'location' => '1087 Budapest, Könyves Kálmán körút 52.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 500 X',
                'licencePlate' => 'TQD-536',
                'year' => 2021,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 46.4,
                'powerkW' => 33.9,
                'engineSize' => 471,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 21800,
                'deposit' => 65400,
                'trafficDate' => '2028-03-30',
                'location' => '1239 Budapest, Haraszti út 42.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 650 R Fenix',
                'licencePlate' => 'PKY-801',
                'year' => 2021,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 93.9,
                'powerkW' => 68.5,
                'engineSize' => 649,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 28000,
                'deposit' => 84000,
                'trafficDate' => '2029-09-15',
                'location' => '1051 Budapest, Bajcsy-Zsilinszky út 24.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB 900 F Hornet',
                'licencePlate' => 'MSA-397',
                'year' => 2003,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 110.0,
                'powerkW' => 80.3,
                'engineSize' => 919,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 30600,
                'deposit' => 91800,
                'trafficDate' => '2028-06-16',
                'location' => '1173 Budapest, Pesti út 237.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB Shine',
                'licencePlate' => 'HZQ-625',
                'year' => 2013,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 10.3,
                'powerkW' => 7.5,
                'engineSize' => 124.6,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 141600,
                'trafficDate' => '2025-08-02',
                'location' => '1151 Budapest, Károlyi Sándor út 76.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CB Twister',
                'licencePlate' => 'FLX-752',
                'year' => 2013,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 9.0,
                'powerkW' => 6.6,
                'engineSize' => 109,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 147600,
                'trafficDate' => '2026-12-03',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CBF Stunner',
                'licencePlate' => 'ZWV-436',
                'year' => 2011,
                'gearbox' => 'Manualis (5 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 11.0,
                'powerkW' => 8.0,
                'engineSize' => 124.7,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 126000,
                'trafficDate' => '2028-04-14',
                'location' => '1037 Budapest, Bojtár utca 43.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CBR 150 R',
                'licencePlate' => 'YKP-583',
                'year' => 2017,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 16.9,
                'powerkW' => 12.3,
                'engineSize' => 149.6,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 110100,
                'trafficDate' => '2029-06-25',
                'location' => '1064 Budapest, Podmaniczky utca 63.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CBR 400 R',
                'licencePlate' => 'TGS-917',
                'year' => 2014,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 46.0,
                'powerkW' => 33.6,
                'engineSize' => 399,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32767,
                'deposit' => 123000,
                'trafficDate' => '2028-11-24',
                'location' => '1126 Budapest, Böszörményi út 38.'
            ],

            [
                'brand' => 'Honda',
                'type' => 'CBR 600 RR',
                'licencePlate' => 'LRF-108',
                'year' => 2016,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 118.0,
                'powerkW' => 86.1,
                'engineSize' => 599,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 32500,
                'deposit' => 97500,
                'trafficDate' => '2025-05-19',
                'location' => '1044 Budapest, Megyeri út 20.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CD 110 Dream',
                'licencePlate' => 'PNZ-476',
                'year' => 2023,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 8.7,
                'powerkW' => 6.3,
                'engineSize' => 109.1,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 27100,
                'deposit' => 81300,
                'trafficDate' => '2026-10-31',
                'location' => '1151 Budapest, Károlyi Sándor út 76.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CG 125',
                'licencePlate' => 'VKM-245',
                'year' => 2022,
                'gearbox' => 'Manualis (4 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 11.0,
                'powerkW' => 8.0,
                'engineSize' => 124,
                'drivingLicence' => 'A1/B',
                'places' => 2,
                'price' => 16100,
                'deposit' => 48300,
                'trafficDate' => '2027-06-19',
                'location' => '1161 Budapest, Rákosi út 88.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'Click 125',
                'licencePlate' => 'GRX-792',
                'year' => 2023,
                'gearbox' => 'Automata',
                'fuel' => 'B',
                'powerLe' => 11.0,
                'powerkW' => 8.0,
                'engineSize' => 125,
                'drivingLicence' => 'A1/B',
                'places' => 2,
                'price' => 18000,
                'deposit' => 54000,
                'trafficDate' => '2028-12-21',
                'location' => '1185 Budapest, Üllői út 780.'
            ],
            [
                'brand' => 'Honda',
                'type' => 'CMX 500 Rebel',
                'licencePlate' => 'JKW-521',
                'year' => 2018,
                'gearbox' => 'Manualis (6 fokozatu)',
                'fuel' => 'B',
                'powerLe' => 46.9,
                'powerkW' => 34.3,
                'engineSize' => 471,
                'drivingLicence' => 'A2',
                'places' => 2,
                'price' => 20000,
                'deposit' => 60000,
                'trafficDate' => '2029-07-07',
                'location' => '1138 Budapest, Váci út 152.'
            ],
            [
                "brand" => "Honda",
                "type" => "VFR 800 X Crossrunner",
                "licencePlate" => "SBD-870",
                "year" => 2015,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 107.0,
                'powerkW' => 78.1,
                "engineSize" => 782,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 127800,
                "trafficDate" => "2028-12-29",
                "location" => "1077 Budapest, Rottenbiller utca 25."
            ],
            [
                "brand" => "Honda",
                "type" => "Crosstourer Highlander",
                "licencePlate" => "NXZ-413",
                "year" => 2014,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 127.4,
                'powerkW' => 93.0,
                "engineSize" => 1237,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 20500,
                "deposit" => 61500,
                "trafficDate" => "2025-02-04",
                "location" => "1103 Budapest, Gyömrői út 50."
            ],
            [
                "brand" => "Honda",
                "type" => "Deauville",
                "licencePlate" => "DQR-658",
                "year" => 2006,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 64.8,
                'powerkW' => 47.3,
                "engineSize" => 680,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 101400,
                "trafficDate" => "2026-03-02",
                "location" => "1151 Budapest, Károlyi Sándor út 76."
            ],
            [
                "brand" => "Honda",
                "type" => "Dio",
                "licencePlate" => "LMF-283",
                "year" => 2014,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 8.0,
                'powerkW' => 5.8,
                "engineSize" => 109,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16600,
                "deposit" => 49800,
                "trafficDate" => "2027-08-28",
                "location" => "1161 Budapest, Rákosi út 88."
            ],
            [
                "brand" => "Honda",
                "type" => "Dream Neo",
                "licencePlate" => "FYC-916",
                "year" => 2014,
                "gearbox" => "Manualis (4 fokozatu)",
                "fuel" => "B",
                'powerLe' => 8.3,
                'powerkW' => 6.0,
                "engineSize" => 109,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16300,
                "deposit" => 48900,
                "trafficDate" => "2028-10-08",
                "location" => "1117 Budapest, Szerémi út 67."
            ],
            [
                "brand" => "Honda",
                "type" => "EVO 6",
                "licencePlate" => "ZWH-543",
                "year" => 2014,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 150.0,
                'powerkW' => 109.5,
                "engineSize" => 1832,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 30400,
                "deposit" => 91200,
                "trafficDate" => "2029-04-12",
                "location" => "1185 Budapest, Üllői út 780."
            ],
            [
                "brand" => "Honda",
                "type" => "Gold Wing Tour",
                "licencePlate" => "TNL-798",
                "year" => 2022,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 124.7,
                'powerkW' => 91.0,
                "engineSize" => 1833,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 110700,
                "trafficDate" => "2028-09-14",
                "location" => "1148 Budapest, Fogarasi út 45."
            ],
            [
                "brand" => "Honda",
                "type" => "Integra",
                "licencePlate" => "PCK-251",
                "year" => 2018,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 54.0,
                'powerkW' => 39.4,
                "engineSize" => 745,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 119400,
                "trafficDate" => "2025-07-01",
                "location" => "1173 Budapest, Pesti út 237."
            ],
            [
                "brand" => "Honda",
                "type" => "Jazz 250",
                "licencePlate" => "QDM-738",
                "year" => 2002,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 19.3,
                'powerkW' => 14.1,
                "engineSize" => 249,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 104700,
                "trafficDate" => "2026-01-12",
                "location" => "1173 Budapest, Pesti út 237."
            ],
            [
                "brand" => "Honda",
                "type" => "Lead 125",
                "licencePlate" => "GVX-493",
                "year" => 2015,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 11.3,
                'powerkW' => 8.3,
                "engineSize" => 124.9,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 117600,
                "trafficDate" => "2027-04-26",
                "location" => "1051 Budapest, Bajcsy-Zsilinszky út 24."
            ],
            [
                "brand" => "Honda",
                "type" => "MSX 125",
                "licencePlate" => "LRB-187",
                "year" => 2019,
                "gearbox" => "Manualis (4 fokozatu)",
                "fuel" => "B",
                'powerLe' => 9.7,
                'powerkW' => 7.1,
                "engineSize" => 124.9,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 15800,
                "deposit" => 47400,
                "trafficDate" => "2028-05-29",
                "location" => "1185 Budapest, Üllői út 780."
            ],
            [
                "brand" => "Honda",
                "type" => "NSC 110 Vision",
                "licencePlate" => "HKY-632",
                "year" => 2013,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 8.3,
                'powerkW' => 6.1,
                "engineSize" => 108,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16300,
                "deposit" => 48900,
                "trafficDate" => "2029-10-20",
                "location" => "1087 Budapest, Könyves Kálmán körút 52."
            ],
            [
                "brand" => "Honda",
                "type" => "PCX 125",
                "licencePlate" => "MTJ-428",
                "year" => 2019,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 12.1,
                'powerkW' => 8.8,
                "engineSize" => 125,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 137700,
                "trafficDate" => "2028-03-19",
                "location" => "1096 Budapest, Haller utca 89."
            ],
            [
                "brand" => "Honda",
                "type" => "Stunner",
                "licencePlate" => "FRZ-915",
                "year" => 2014,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 11.6,
                'powerkW' => 8.5,
                "engineSize" => 124.7,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 31400,
                "deposit" => 94200,
                "trafficDate" => "2025-09-23",
                "location" => "1096 Budapest, Haller utca 89."
            ],
            [
                "brand" => "Honda",
                "type" => "Unicorn",
                "licencePlate" => "VCM-578",
                "year" => 2022,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 12.7,
                'powerkW' => 9.3,
                "engineSize" => 162.7,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 30200,
                "deposit" => 90600,
                "trafficDate" => "2026-07-30",
                "location" => "1151 Budapest, Károlyi Sándor út 76."
            ],
            [
                "brand" => "Honda",
                "type" => "Wave 110i",
                "licencePlate" => "PKR-846",
                "year" => 2017,
                "gearbox" => "Manualis (4 fokozatu)",
                "fuel" => "B",
                'powerLe' => 8.4,
                'powerkW' => 6.1,
                "engineSize" => 109.1,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 15100,
                "deposit" => 45300,
                "trafficDate" => "2027-11-15",
                "location" => '1126 Budapest, Böszörményi út 38.'
            ],
            [
                "brand" => "Honda",
                "type" => "X Blade",
                "licencePlate" => "YSD-314",
                "year" => 2022,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 13.7,
                'powerkW' => 10.0,
                "engineSize" => 162.7,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 26600,
                "deposit" => 79800,
                "trafficDate" => "2028-06-09",
                "location" => "1151 Budapest, Károlyi Sándor út 76."
            ],
            [
                "brand" => "Super Soco",
                "type" => "CPX",
                "licencePlate" => "GZV-509",
                "year" => 2023,
                "gearbox" => "Automata",
                "fuel" => "E",
                'powerLe' => 5.4,
                'powerkW' => 3.9,
                "engineSize" => 146.4,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 17100,
                "deposit" => 51300,
                "trafficDate" => "2029-01-14",
                "location" => "1126 Budapest, Böszörményi út 38."
            ],
            [
                "brand" => "Super Soco",
                "type" => "TC Titan",
                "licencePlate" => "JLW-839",
                "year" => 2022,
                "gearbox" => "Automata",
                "fuel" => "E",
                'powerLe' => 24.1,
                'powerkW' => 17.6,
                "engineSize" => 243.2,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 140400,
                "trafficDate" => "2028-05-28",
                "location" => "1037 Budapest, Bojtár utca 43."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Aerox 155",
                "licencePlate" => "QWF-760",
                "year" => 2022,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 14.8,
                'powerkW' => 10.8,
                "engineSize" => 155,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 26200,
                "deposit" => 78600,
                "trafficDate" => "2025-10-06",
                "location" => "1239 Budapest, Haraszti út 42."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Cygnus Alpha",
                "licencePlate" => "NLM-182",
                "year" => 2018,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 7.2,
                'powerkW' => 5.3,
                "engineSize" => 113,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 17400,
                "deposit" => 52200,
                "trafficDate" => "2026-04-08",
                "location" => "1195 Budapest, Ady Endre út 134."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Fazer",
                "licencePlate" => "SHP-649",
                "year" => 2028,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 14.0,
                'powerkW' => 10.2,
                "engineSize" => 153,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 111000,
                "trafficDate" => "2027-03-18",
                "location" => "1077 Budapest, Rottenbiller utca 25."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Fazer 8",
                "licencePlate" => "FQX-329",
                "year" => 2013,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 104.7,
                'powerkW' => 76.4,
                "engineSize" => 779,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 24600,
                "deposit" => 73800,
                "trafficDate" => "2028-02-07",
                "location" => "1012 Budapest, Logodi utca 34."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Fino 125",
                "licencePlate" => "RLJ-470",
                "year" => 2023,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 9.4,
                'powerkW' => 6.9,
                "engineSize" => 125,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 18200,
                "deposit" => 54600,
                "trafficDate" => "2029-08-03",
                "location" => "1195 Budapest, Ady Endre út 134."
            ],
            [
                "brand" => "Yamaha",
                "type" => "EGO Avantiz",
                "licencePlate" => "TXW-953",
                "year" => 2020,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 9.4,
                'powerkW' => 6.9,
                "engineSize" => 124,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16100,
                "deposit" => 48300,
                "trafficDate" => "2028-02-25",
                "location" => "1051 Budapest, Bajcsy-Zsilinszky út 24."
            ],
            [
                "brand" => "Yamaha",
                "type" => "EGO Solariz",
                "licencePlate" => "BZC-218",
                "year" => 2020,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 9.4,
                'powerkW' => 6.9,
                "engineSize" => 125,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 18900,
                "deposit" => 56700,
                "trafficDate" => "2025-03-31",
                "location" => "1117 Budapest, Szerémi út 67."
            ],
            [
                "brand" => "Yamaha",
                "type" => "FJ-09",
                "licencePlate" => "MHF-475",
                "year" => 2016,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 115.0,
                'powerkW' => 83.9,
                "engineSize" => 847,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 108600,
                "trafficDate" => "2026-09-04",
                "location" => "1239 Budapest, Haraszti út 42."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Freego S",
                "licencePlate" => "VNZ-684",
                "year" => 2021,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 9.4,
                'powerkW' => 6.9,
                "engineSize" => 125,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 19800,
                "deposit" => 59400,
                "trafficDate" => "2027-12-22",
                "location" => "1096 Budapest, Haller utca 89."
            ],
            [
                "brand" => "Yamaha",
                "type" => "Gladiator",
                "licencePlate" => "KSW-371",
                "year" => 2007,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 10.7,
                'powerkW' => 7.8,
                "engineSize" => 123.7,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16700,
                "deposit" => 50100,
                "trafficDate" => "2028-11-18",
                "location" => "1087 Budapest, Könyves Kálmán körút 52."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Address",
                "licencePlate" => "PLH-890",
                "year" => 2018,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 9.3,
                'powerkW' => 6.8,
                "engineSize" => 113,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 22400,
                "deposit" => 67200,
                "trafficDate" => "2029-05-06",
                "location" => "1103 Budapest, Gyömrői út 50."
            ],
            [
                "brand" => "Suzuki",
                "type" => "B-King",
                "licencePlate" => "FRV-209",
                "year" => 2012,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 181.0,
                'powerkW' => 132.1,
                "engineSize" => 1340,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 28300,
                "deposit" => 84900,
                "trafficDate" => "2028-01-15",
                "location" => "1051 Budapest, Bajcsy-Zsilinszky út 24."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Boulevard S40",
                "licencePlate" => "DNY-742",
                "year" => 2021,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 56.0,
                'powerkW' => 43.6,
                "engineSize" => 652,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 22200,
                "deposit" => 66600,
                "trafficDate" => "2025-06-27",
                "location" => "1223 Budapest, Nagytétényi út 190."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Gixxer 250",
                "licencePlate" => "ZWQ-658",
                "year" => 2028,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 26.5,
                'powerkW' => 19.3,
                "engineSize" => 249,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 22200,
                "deposit" => 66600,
                "trafficDate" => "2026-12-20",
                "location" => "1044 Budapest, Megyeri út 20."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Hayate EP",
                "licencePlate" => "PTL-303",
                "year" => 2018,
                "gearbox" => "Manualis (4 fokozatu)",
                "fuel" => "B",
                'powerLe' => 8.7,
                'powerkW' => 6.4,
                "engineSize" => 113,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16600,
                "deposit" => 49800,
                "trafficDate" => "2027-07-01",
                "location" => "1161 Budapest, Rákosi út 88."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Intruder Classic 400",
                "licencePlate" => "VXJ-940",
                "year" => 2015,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 33.0,
                'powerkW' => 24.1,
                "engineSize" => 399,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 102600,
                "trafficDate" => "2028-09-12",
                "location" => "1151 Budapest, Károlyi Sándor út 76."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Katana",
                "licencePlate" => "LBF-217",
                "year" => 2022,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 152.0,
                'powerkW' => 110.9,
                "engineSize" => 999,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 20200,
                "deposit" => 60600,
                "trafficDate" => "2029-03-08",
                "location" => "1012 Budapest, Logodi utca 34."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Shooter 115 FI",
                "licencePlate" => "HMX-679",
                "year" => 2018,
                "gearbox" => "Manualis (4 fokozatu)",
                "fuel" => "B",
                'powerLe' => 9.3,
                'powerkW' => 6.8,
                "engineSize" => 113,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16400,
                "deposit" => 49200,
                "trafficDate" => "2028-10-02",
                "location" => "1021 Budapest, Hűvösvölgyi út 136."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Skywave 650 LX",
                "licencePlate" => "QRJ-501",
                "year" => 2005,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 49.6,
                'powerkW' => 36.2,
                "engineSize" => 638,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 110700,
                "trafficDate" => "2025-12-14",
                "location" => "1211 Budapest, Szállító utca 6."
            ],
            [
                "brand" => "Suzuki",
                "type" => "Slingshot Plus",
                "licencePlate" => "FYC-318",
                "year" => 2017,
                "gearbox" => "Manualis (5 fokozatu)",
                "fuel" => "B",
                'powerLe' => 14.8,
                'powerkW' => 10.8,
                "engineSize" => 124,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 25400,
                "deposit" => 76200,
                "trafficDate" => "2026-02-07",
                "location" => "1117 Budapest, Szerémi út 67."
            ],
            [
                "brand" => "Suzuki",
                "type" => "V-Strom 1050DE Adventure",
                "licencePlate" => "GYD-764",
                "year" => 2028,
                "gearbox" => "Manualis (6 fokozatu)",
                "fuel" => "B",
                'powerLe' => 100.0,
                'powerkW' => 73.0,
                "engineSize" => 1037,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 28100,
                "deposit" => 84300,
                "trafficDate" => "2027-05-05",
                "location" => "1223 Budapest, Nagytétényi út 190."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Belville 125 RS",
                "licencePlate" => "MSK-201",
                "year" => 2019,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 11.0,
                'powerkW' => 8.0,
                "engineSize" => 125,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 17900,
                "deposit" => 53700,
                "trafficDate" => "2028-08-16",
                "location" => "1185 Budapest, Üllői út 780."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Citystar 125 RS",
                "licencePlate" => "PKX-928",
                "year" => 2019,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 14.2,
                'powerkW' => 10.4,
                "engineSize" => 124.8,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 32767,
                "deposit" => 116100,
                "trafficDate" => "2029-07-30",
                "location" => "1185 Budapest, Üllői út 780."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Geopolis 125 Premium",
                "licencePlate" => "ZWJ-563",
                "year" => 2008,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 15.0,
                'powerkW' => 10.9,
                "engineSize" => 124.8,
                "drivingLicence" => "A2",
                "places" => 2,
                "price" => 20400,
                "deposit" => 61200,
                "trafficDate" => "2027-06-08",
                "location" => "1148 Budapest, Fogarasi út 45."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Kisbee 50 RS",
                "licencePlate" => "LSH-429",
                "year" => 2021,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 3.6,
                'powerkW' => 2.6,
                "engineSize" => 49.9,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 16500,
                "deposit" => 49500,
                "trafficDate" => "2025-11-30",
                "location" => "1096 Budapest, Haller utca 89."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Speedfight 50",
                "licencePlate" => "KTV-832",
                "year" => 2023,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 3.0,
                'powerkW' => 2.2,
                "engineSize" => 49.9,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 18500,
                "deposit" => 55500,
                "trafficDate" => "2026-03-23",
                "location" => "1096 Budapest, Haller utca 89."
            ],
            [
                "brand" => "Peugeot",
                "type" => "Streetzone 50",
                "licencePlate" => "NPJ-187",
                "year" => 2024,
                "gearbox" => "Automata",
                "fuel" => "B",
                'powerLe' => 3.5,
                'powerkW' => 2.6,
                "engineSize" => 49.9,
                "drivingLicence" => "A1/B",
                "places" => 2,
                "price" => 25600,
                "deposit" => 76800,
                "trafficDate" => "2027-09-26",
                "location" => "1103 Budapest, Gyömrői út 50."
            ]


        ]);
    }
}